name: Docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  check:
    uses: anolishq/.github/.github/workflows/docs-check.yml@0f4d8cd3c04dcb17fe128248a147b237c1465e0c # v2
