name: Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'  # Weekly Monday 6am UTC
  workflow_dispatch:

jobs:
  collect:
    uses: anolishq/.github/.github/workflows/metrics.yml@fa90acda2a76e1a81fb6266be94f50d7d2fb6fd0 # v1
